# Generated by Django 4.1.7 on 2023-03-21 18:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_author_added_date_author_updated_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('review', models.IntegerField(choices=[(1, 'Poor'), (2, 'Inefficient'), (3, 'Adequate'), (4, 'Effective'), (5, 'Excellent')])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
