# Generated by Django 4.1.7 on 2023-03-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_author_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name='book',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
    ]
