# Generated by Django 4.1.7 on 2023-03-21 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_author_score_book_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='score',
            new_name='rating',
        ),
    ]
