# Generated by Django 4.1.7 on 2023-03-21 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_rename_score_book_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
